### ISSUE TITLE
command "pandoc.render" not found 

### ISSUE THREAD

**Issue by hisaotsu** [dfinke/vscode-pandoc#25]
I have a following setting, but I get pandoc.render not found message.
I would appreciate it what I can look into to solve the problem.

macOS : 10.13.6 (High Sierra)
Visual Studio Code 1.28.0-insider
pdflatex 

MacBookPro:Downloads myuser $ pandoc --version
pandoc 2.3
(.....)
// pdftex and lualatex are part of the latest MacTex package.
MacBookPro:Downloads hisaotsu$ pdftex --version
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)
kpathsea version 6.3.0
(.....)
MacBookPro:Downloads myuser $ lualatex --version
This is LuaTeX, Version 1.07.0 (TeX Live 2018)

Running pandoc alone seems to complete  fine.

MacBookPro:Downloads myuser $ pandoc test.txt -o test.pdf
MacBookPro:Downloads myuser $ echo $?
0
MacBookPro:Downloads myuser $ ls -l test*
-rw-r--r--  1 myuser  staff  46236  9 22 08:47 test.pdf
-rw-r--r--@ 1 mauser  staff    108  9 22 08:35 test.txt

What logs and options I can look into to solve this issue?

**Comment by feeeper** [comment]
@hisaotsu Open Developer Tools (Help -> Toggle Developer Tools) and run the extension. You'll see some debug information that may help you.

**Comment by hisaotsu** [comment]
Thank you for spending your time for me.
After a few tries, I found that pandoc and some other dependent libraries are out-dated.
I ran "brew update," disabled your extension, then enabled it.  This seems to solve the problem even though I am unsure of why.   Than you for your kind help!
