### ISSUE TITLE
Setting additional pandoc options

### ISSUE THREAD

**Issue by satokaz** [dfinke/vscode-pandoc#5]
The default pandoc option of some can not be converted Markdown document.
For example, to convert the multi-byte of the Markdown document that contains the Japanese will must have the appropriate option settings.

I need a mechanism to be set separately the options.
It added the following features.

https://github.com/satokaz/vscode-pandoc/tree/pandoc_options

if so there is no problem with the implementation, I will do a pull request.

## **Setting additional pandoc options**

 1. choose 'Preference -> UserSettings'
 2. Find: pandoc in Default Settings
 3. Copy and paste to settings.json

example: 
```
//-------- Pandoc Option Configuration --------

// pandoc .pdf output option template that you would like to use
"pandoc.pdfOptString": "",

// pandoc .docx output option template that you would like to use
"pandoc.docxOptString": "",

// pandoc .html output option template that you would like to use
"pandoc.htmlOptString": ""
```

* if necessary to set options for each output format.
 * default: `$ pandoc inFile.md -o outFile.{pdf|word|html}`

## Example: Setting for Japanese document :　 

* PDF  

  `"pandoc.pdfOptString": "--latex-engine=lualatex -V documentclass=ltjarticle -V geometry:a4paper -V geometry:margin=2.5cm -V geometry:nohead",`  

  `--latex-engine=lualatex:`: need to create a Japanese PDF  
  `-V documentclass=ltjarticle`: need to create a Japanese PDF  
  `-V geometry:a4paper -V geometry:margin=2.5cm -V geometry:nohead"`: geometory options  

* Word(docx)  

  `pandoc.docxOptString": "",`  
  It will work even if you do not set the options.

* HTML5   

  `"pandoc.htmlOptString": "-s -t html5"`

  `-s`: produce a standalone document  
  `-t html5`: HTML5 output format
  
For more information please refer to the [Pandoc User’s Guide](http://pandoc.org/README.html).

**Comment by dfinke** [comment]
Thanks for the comment. At first glance it looks good. Let me review. Feel free to do a PR and we can review.

**Comment by satokaz** [comment]
ok, thanks.

**Comment by dfinke** [comment]
Thank you for the great update.
